### ISSUE TITLE
Which datasets to download

### ISSUE THREAD

**Issue by TerenceXue-tech** [robot-learning-freiburg/MoMa-LLM#2]
In step2, Which datasets to download?

**Comment by dHonerkamp** [comment]
Hi,

You need the interactive iGibson dataset, the one detailed in the first part of the docs: https://stanfordvl.github.io/iGibson/dataset.html#downloading-the-igibson-dataset-of-scenes-and-the-behavior-dataset-of-objects

Hope that helps.

**Comment by TerenceXue-tech** [comment]
Thanks! It works. By the way, we are interested in this work and want to explore new tasks using Moma.


-----原始邮件-----
发件人:dHonerkamp ***@***.***>
发送时间:2024-07-29 16:36:29 (星期一)
收件人: robot-learning-freiburg/MoMa-LLM ***@***.***>
抄送: TerenceXue-tech ***@***.***>, Author ***@***.***>
主题: Re: [robot-learning-freiburg/MoMa-LLM] Which datasets to download (Issue #2)






Hi,

You need the interactive iGibson dataset, the one detailed in the first part of the docs: https://stanfordvl.github.io/iGibson/dataset.html#downloading-the-igibson-dataset-of-scenes-and-the-behavior-dataset-of-objects

Hope that helps.

**Comment by TerenceXue-tech** [comment]
We hope to utilize Moma's interactive navigation system combined with Code as Policy (https://code-as-policies.github.io/) to execute diverse tasks. Specifically, we aim to expand the limited action space (navigate, go and open, close, explore, done) , enabling a mobile manipulation robot  in home environments to perform various tasks beyond item retrieval.


-----原始邮件-----
发件人:dHonerkamp ***@***.***>
发送时间:2024-07-29 20:45:19 (星期一)
收件人: robot-learning-freiburg/MoMa-LLM ***@***.***>
抄送: TerenceXue-tech ***@***.***>, Author ***@***.***>
主题: Re: [robot-learning-freiburg/MoMa-LLM] Which datasets to download (Issue #2)






Great, glad to hear 😊
