### ISSUE TITLE
paper from

### ISSUE THREAD

**Issue by liaokaiyao** [robot-learning-freiburg/MoMa-LLM#3]
You mentioned  . Chen et al. provide a possible reference implementation: they deploy an RTAB-node for localization and mapping. This can be extended to semantic labels through an additional RTAB-node that listens to the semantic masks, to then fuse the resulting point clouds.                                        May I ask which paper this comes from

**Comment by dHonerkamp** [comment]
Hi, sorry it seems that the citation went missing. This is referring to the following paper:

J. Chen, G. Li, S. Kumar, B. Ghanem, and F. Yu, “How to not train your dragon: Training-free embodied object goal navigation with semantic frontiers,” Robotics: Science and Systems, 2023.

We will add the reference in the final version.

**Comment by liaokaiyao** [comment]
OK，thank you！
